### ISSUE TITLE
module too verbose, breaks TMB build

### ISSUE THREAD

**Issue by alko989** [DTUAqua/hpc_setup#7]
While building TMB using `make install-metis-full`, there is an issue with the verbosity of `module`, it adds the message "Loaded dependency [gcc/9.2.0]:... " )into the CXXFLAGS. The g++ call is below.

After digging for some hours, I think the solution is to add `-s` when calling `module load` in `R` to make it quieter

`module load -s intel/2017.4.196.mkl 2> /dev/null`
`module load -s gcc/9.2.0 geos/3.8.2 gdal/3.2.0 udunits2/2.2.26 2> /dev/null`

-- 
The g++ call, in the last line is the message that is inserted into the flags: 

`g++ -L/zhome/6c/1/73877/git-repos/hpc_setup/adcomp/SuiteSparse-5.7.1/lib -shared -Wl,-soname -Wl,libcholmod.so.3 -Wl,--no-undefined -fopenmp cholmod_aat.o cholmod_add.o cholmod_band.o cholmod_change_factor.o cholmod_common.o cholmod_complex.o cholmod_copy.o cholmod_dense.o cholmod_error.o cholmod_factor.o cholmod_memory.o cholmod_sparse.o cholmod_transpose.o cholmod_triplet.o cholmod_version.o cholmod_check.o cholmod_read.o cholmod_write.o cholmod_amd.o cholmod_analyze.o cholmod_colamd.o cholmod_etree.o cholmod_factorize.o cholmod_postorder.o cholmod_rcond.o cholmod_resymbol.o cholmod_rowcolcounts.o cholmod_rowfac.o cholmod_solve.o cholmod_spsolve.o cholmod_drop.o cholmod_horzcat.o cholmod_norm.o cholmod_scale.o cholmod_sdmult.o cholmod_ssmult.o cholmod_submatrix.o cholmod_vertcat.o cholmod_symmetry.o cholmod_rowadd.o cholmod_rowdel.o cholmod_updown.o cholmod_super_numeric.o cholmod_super_solve.o cholmod_super_symbolic.o cholmod_ccolamd.o cholmod_csymamd.o cholmod_metis.o cholmod_nesdis.o cholmod_camd.o cholmod_l_aat.o cholmod_l_add.o cholmod_l_band.o cholmod_l_change_factor.o cholmod_l_common.o cholmod_l_complex.o cholmod_l_copy.o cholmod_l_dense.o cholmod_l_error.o cholmod_l_factor.o cholmod_l_memory.o cholmod_l_sparse.o cholmod_l_transpose.o cholmod_l_triplet.o cholmod_l_version.o cholmod_l_check.o cholmod_l_read.o cholmod_l_write.o cholmod_l_amd.o cholmod_l_analyze.o cholmod_l_colamd.o cholmod_l_etree.o cholmod_l_factorize.o cholmod_l_postorder.o cholmod_l_rcond.o cholmod_l_resymbol.o cholmod_l_rowcolcounts.o cholmod_l_rowfac.o cholmod_l_solve.o cholmod_l_spsolve.o cholmod_l_drop.o cholmod_l_horzcat.o cholmod_l_norm.o cholmod_l_scale.o cholmod_l_sdmult.o cholmod_l_ssmult.o cholmod_l_submatrix.o cholmod_l_vertcat.o cholmod_l_symmetry.o cholmod_l_rowadd.o cholmod_l_rowdel.o cholmod_l_updown.o cholmod_l_super_numeric.o cholmod_l_super_solve.o cholmod_l_super_symbolic.o cholmod_l_ccolamd.o cholmod_l_csymamd.o cholmod_l_metis.o cholmod_l_nesdis.o cholmod_l_camd.o -o /zhome/6c/1/73877/git-repos/hpc_setup/adcomp/SuiteSparse-5.7.1/lib/libcholmod.so.3.0.14 -lm -lrt -Wl,-rpath=/zhome/6c/1/73877/git-repos/hpc_setup/adcomp/SuiteSparse-5.7.1/lib -lamd -lcolamd -lsuitesparseconfig -lccolamd -lcamd -lmetis -llapack Loaded dependency [gcc/9.2.0]: binutils/2.29
`

**Comment by kaskr** [comment]
It seems I've been struggling with something similar a while back:
https://github.com/DTUAqua/hpc_setup/commit/c2c927a0e68f5302afca3d2041b80014c8335e35
Wasn't aware of the extra `-s` option to module load, and wonder if/why it ever worked without. In any case the more silent the better... You mind sending a PR?
